export { recipientAdapter } from './recipientAdapter'
export { senderAdapter } from './senderAdapter'
export { storeAdapters } from './storeAdapters'
export { postcardsAdapter } from './postcardsAdapter'
export { cardPieFavoritesAdapter } from './cardPieFavoritesAdapter'
export { imageAdapter } from './imageAdapter'
export { cardtextAdapter } from './cardtextAdapter'
