import { all, fork } from 'redux-saga/effects'
import {
  cardEditorSaga,
  editorPieProcessSaga,
  envelopeToolbarSaga,
  envelopeFormSyncSaga,
  envelopeProcessSaga,
  addressBookSyncSaga,
  cardtextProcessSaga,
  sectionEditorMenuSaga,
  cardphotoProcessSaga,
  cardCalendarPreviewSaga,
  hydrateAppSession,
  watchSessionChanges,
  addressSaveSaga,
  cardPanelToolbarSaga,
  watchDateToolbar,
  watchCartToolbar,
  watchCartRemove,
  watchPostcardPieToolbar,
  rightSidebarToolbarSaga,
  watchHistoryToolbar,
  watchExclusiveListPanels,
  watchApplyArchiveSection,
  watchNotebookOrchestrator,
  watchNotebookStateBridge,
  watchNotebookStripTabSync,
  watchCartCalendarDatePick,
} from '../middleware'

export function* rootSaga() {
  yield fork(hydrateAppSession)

  yield all([
    fork(watchSessionChanges),
    fork(cardEditorSaga),
    fork(editorPieProcessSaga),

    // fork(envelopeSaga),

    fork(envelopeToolbarSaga),
    fork(envelopeFormSyncSaga),
    fork(envelopeProcessSaga),
    fork(addressBookSyncSaga),
    fork(addressSaveSaga),
    fork(cardtextProcessSaga),
    // fork(cardphotoToolbarSaga),
    // fork(cardphotoHistorySaga),
    fork(cardphotoProcessSaga),
    fork(cardCalendarPreviewSaga),
    fork(sectionEditorMenuSaga),
    fork(rightSidebarToolbarSaga),
    fork(cardPanelToolbarSaga),
    fork(watchDateToolbar),
    fork(watchCartToolbar),
    fork(watchCartRemove),
    fork(watchPostcardPieToolbar),
    fork(watchHistoryToolbar),
    fork(watchExclusiveListPanels),
    fork(watchApplyArchiveSection),
    fork(watchNotebookOrchestrator),
    fork(watchNotebookStateBridge),
    fork(watchNotebookStripTabSync),
    fork(watchCartCalendarDatePick),
  ])
}
