import { layoutActions } from './layoutSlice'

export const {
  addSizeCard,
  addSizeMiniCard,
  addRemSize,
  addChoiceSection,
  addIndexDb,
  addMemoryCrop,
  setChoiceMemorySection,
  setFullCardPersonalId,
  setBtnToolbar,
  setActiveSections,
  setDateCartCards,
  setLockDateCartCards,
  setCartCards,
  setLockExpendMemoryCard,
  setChoiceSave,
  setChoiceClip,
  setSliderLetter,
  setSliderLine,
  setDeltaEnd,
  setSelectedSection,
  setDeleteSection,
  setPersonalId,
  setFullCard,
  setAddFullCard,
  setExpendMemoryCard,
  setMaxCardsList,
} = layoutActions
