export { stockImagesAdapter } from './postcard/stockImagesAdapter'
export { userImagesAdapter } from './postcard/userImagesAdapter'
export { cardtextAdapter } from './postcard/cardtextAdapter'
export { senderAddressAdapter } from './postcard/senderAddressAdapter'
export { recipientAddressAdapter } from './postcard/recipientAddressAdapter'
