export { stockImagesAdapter } from './storeAdapters/stockImagesAdapter'
export { userImagesAdapter } from './storeAdapters/userImagesAdapter'
export { cardtextAdapter } from './storeAdapters/cardtextAdapter'
export { senderAddressAdapter } from './storeAdapters/senderAdapter'
export { recipientAddressAdapter } from './storeAdapters/recipientAdapter'
