export const ADD_CARDPHOTO = 'ADD_CARDPHOTO'
export const ADD_CARDTEXT = 'ADD_CARDTEXT'
export const ADD_ENVELOPE = 'ADD_ENVELOPE'
export const ADD_DATE = 'ADD_DATE'
export const ADD_AROMA = 'ADD_AROMA'
export const DELETE_SECTION = 'DELETE_SECTION'
